### ISSUE TITLE
Installing TN5250J in ubuntu with Java GUI

### ISSUE THREAD

**Issue by prajwalaa110** [tn5250j/tn5250j#75]
I am trying to install Tn5250J emulator in ubuntu machine. I have JDK 8 is already installed on machine. Whenever i try to run the installer jar in ubuntu it gives following error.

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit

To solve it, I set DISPLAY variable, after that i am getting following exception

Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:231)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:198)
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
        at org.tn5250j.tools.GUIGraphicsUtils.createImageIcon(Unknown Source)
        at org.tn5250j.gui.TN5250jSplashScreen.<init>(Unknown Source)
        at org.tn5250j.My5250.<init>(Unknown Source)
        at org.tn5250j.My5250.main(Unknown Source)
I checked TN5250J official site for installation,They have given only one command, the same i am following but getting above errors. Please let me know how i can resolve the above issue and install TN5250J emulator successfully in ubuntu

**Comment by szsascha** [comment]
Just to be sure: Are you using a desktop version of Ubuntu?

**Comment by prajwalaa110** [comment]
Apologies for not mentioning in the first place.  I am trying to install on AWS - Ubuntu installation

**Comment by szsascha** [comment]
@prajwalaa110 No problem. So I assume that it is a Ubuntu server installation and you're connected via ssh oder web console.

You need a desktop environment (X11) to run tn5250j. So what you are trying to do is not possible at the moment.

**Comment by szsascha** [comment]
@prajwalaa110 But you could use a simple telnet to connect to an i :)

**Comment by prajwalaa110** [comment]
@szsascha  Thank you very much for the quick reply.  Any links on google to help me doing that?  Thanks a million in advance.

**Comment by szsascha** [comment]
@prajwalaa110 Should be pretty simple:
1. Type in the following to install telnet: apt-get install telnet
2. Now connect to the server: telnet SERVERADDRESS PORT
(For example: telnet pub400.com 22)

Please let me know if it's working.
